services:

  postgres-db:
    image: tiredofit/postgres:16
    container_name: postgres-db
    volumes:
      - ./logs:/logs
      - ./db:/var/lib/postgresql/data
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=postgres-db

      - SUPERUSER_PASS=superuser

      - DB_NAME=database
      - DB_USER=user
      - DB_PASS=password

    networks:
      - services
    restart: always

networks:
  services:
    external: false
